-- public.aptitudes definition

-- Drop table

-- DROP TABLE public.aptitudes;

CREATE TABLE public.aptitudes (
                                aptitud_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                descripcion varchar(255) NULL,
                                CONSTRAINT aptitudes_pkey PRIMARY KEY (aptitud_id)
);


-- public.orders definition

-- Drop table

-- DROP TABLE public.orders;

CREATE TABLE public.orders (
                             order_id bigserial NOT NULL,
                             customer_name varchar(255) NOT NULL,
                             customer_email varchar(255) NULL,
                             order_date varchar(255) NULL,
                             status varchar(255) NULL,
                             total float4 NULL,
                             CONSTRAINT pk_orders PRIMARY KEY (order_id)
);


-- public.products definition

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE public.products (
                               product_id bigserial NOT NULL,
                               "name" varchar(255) NOT NULL,
                               description varchar(255) NULL,
                               price float4 NOT NULL,
                               stock int4 NULL,
                               created_at timestamptz NULL,
                               CONSTRAINT pk_products PRIMARY KEY (product_id)
);


-- public.secciones definition

-- Drop table

-- DROP TABLE public.secciones;

CREATE TABLE public.secciones (
                                seccion_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                horas_diarias int4 NULL,
                                nombre varchar(255) NULL,
                                CONSTRAINT secciones_pkey PRIMARY KEY (seccion_id)
);


-- public.tiendas definition

-- Drop table

-- DROP TABLE public.tiendas;

CREATE TABLE public.tiendas (
                              tienda_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              direccion varchar(255) NULL,
                              nombre varchar(255) NULL,
                              CONSTRAINT tiendas_pkey PRIMARY KEY (tienda_id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                            username varchar(255) NOT NULL,
                            "password" varchar(255) NOT NULL,
                            "role" varchar(255) NOT NULL,
                            CONSTRAINT pk_usuarios PRIMARY KEY (username)
);


-- public.order_lines definition

-- Drop table

-- DROP TABLE public.order_lines;

CREATE TABLE public.order_lines (
                                  line_id bigserial NOT NULL,
                                  order_id int8 NOT NULL,
                                  product_id int8 NOT NULL,
                                  quantity int4 NOT NULL,
                                  unit_price float4 NOT NULL,
                                  CONSTRAINT pk_order_lines PRIMARY KEY (line_id),
                                  CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE CASCADE,
                                  CONSTRAINT fk_order_lines_product FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);


-- public.seccion_aptitud definition

-- Drop table

-- DROP TABLE public.seccion_aptitud;

CREATE TABLE public.seccion_aptitud (
                                      seccion_aptitud_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      aptitud_id int8 NULL,
                                      seccion_id int8 NULL,
                                      CONSTRAINT seccion_aptitud_pkey PRIMARY KEY (seccion_aptitud_id),
                                      CONSTRAINT fkodm8jxx9n0jx0f032l1e4o60k FOREIGN KEY (aptitud_id) REFERENCES public.aptitudes(aptitud_id),
                                      CONSTRAINT fkok3q62xyo2xq0jp0faohmfcet FOREIGN KEY (seccion_id) REFERENCES public.secciones(seccion_id)
);


-- public.trabajadores definition

-- Drop table

-- DROP TABLE public.trabajadores;

CREATE TABLE public.trabajadores (
                                   trabajador_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   dni varchar(255) NULL,
                                   nombre varchar(255) NULL,
                                   tienda_id int8 NULL,
                                   CONSTRAINT trabajadores_pkey PRIMARY KEY (trabajador_id),
                                   CONSTRAINT fk5wbo5tg8mcvfk52dbadjna6ha FOREIGN KEY (tienda_id) REFERENCES public.tiendas(tienda_id)
);


-- public.aptitud_trabajador definition

-- Drop table

-- DROP TABLE public.aptitud_trabajador;

CREATE TABLE public.aptitud_trabajador (
                                         aptitud_trabajador_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                         aptitud_id int8 NULL,
                                         trabajador_id int8 NULL,
                                         CONSTRAINT aptitud_trabajador_pkey PRIMARY KEY (aptitud_trabajador_id),
                                         CONSTRAINT fkbpegensaas808s1iwo2kw7sc FOREIGN KEY (trabajador_id) REFERENCES public.trabajadores(trabajador_id),
                                         CONSTRAINT fkompmojrcg6ah71akn325tdfro FOREIGN KEY (aptitud_id) REFERENCES public.aptitudes(aptitud_id)
);


-- public.seccion_trabajador definition

-- Drop table

-- DROP TABLE public.seccion_trabajador;

CREATE TABLE public.seccion_trabajador (
                                         seccion_trabajador_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                         seccion_id int8 NULL,
                                         trabajador_id int8 NULL,
                                         CONSTRAINT seccion_trabajador_pkey PRIMARY KEY (seccion_trabajador_id),
                                         CONSTRAINT fk6nixx2xcymr1uyut7vn5c53vw FOREIGN KEY (seccion_id) REFERENCES public.secciones(seccion_id),
                                         CONSTRAINT fkcjcp0y9i9cykh1thl7e6e687a FOREIGN KEY (trabajador_id) REFERENCES public.trabajadores(trabajador_id)
);
